// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbD5Pn8Ej1YKl3Ug_RLvyIoLJCD8GXJc',
    appId: '1:160080045451:web:50d60206a2a1d2c7f77b8e',
    messagingSenderId: '160080045451',
    projectId: 'study-app-af28f',
    authDomain: 'study-app-af28f.firebaseapp.com',
    storageBucket: 'study-app-af28f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8mPWo8gdGSRlS2K6ZYDN67i404rszKY',
    appId: '1:160080045451:android:a47494c5c358262cf77b8e',
    messagingSenderId: '160080045451',
    projectId: 'study-app-af28f',
    storageBucket: 'study-app-af28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYSQPWnBT7ryXsJv4KXBHKN_8z8bO43U',
    appId: '1:160080045451:ios:9a5d6da6abf04ccff77b8e',
    messagingSenderId: '160080045451',
    projectId: 'study-app-af28f',
    storageBucket: 'study-app-af28f.appspot.com',
    iosClientId: '160080045451-8opq1vfuqvjps7bp45hcfbln597n4co2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYSQPWnBT7ryXsJv4KXBHKN_8z8bO43U',
    appId: '1:160080045451:ios:474ee97f4ad3db48f77b8e',
    messagingSenderId: '160080045451',
    projectId: 'study-app-af28f',
    storageBucket: 'study-app-af28f.appspot.com',
    iosClientId: '160080045451-hap7mje0n1u5fom07jgci3g41cbcke74.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppProject.RunnerTests',
  );
}
